-- composter/init.lua

-- Minetest mod: composter
-- See README.txt for licensing and other information.

dofile(minetest.get_modpath("zero_loader").."/init.lua")
zero_load('composter',{"common", "nodes", "crafts"})

-- seconds before the next composting validation
seconds_to_compost = 5
composting_chance = 50
-- items that can be generated by composting
generate_items = {
  {
    name = "nodes_nature:loam",
    chance = 10,
    cost = 1,
  },
  {
    name = "tech:wood_ash_block",
    chance = 20,
    cost = 2,
  },
}

-- composter block

function get_composter_formspec(compost)
    local formspec = "size[8,4.8]"..
        "label[0,0;Composter: "..compost.."%]"..
        "list[current_name;main;0,0.5;3,2]"..
        "list[current_name;output;5,0.5;3,2]"..
        "list[current_player;main;0,3;8,4;]"..
        "listring[current_name;main]"..
        "listring[current_name;output]"..
        "listring[current_player;main]"..
        "image[3.5,1;1,1;composter_arrow.png;]"
    return formspec
end


